crud_django/animals/urls.py
from django.urls import path , include
from . import views

app_name='aplication'
urlpatterns = [
    #ex : /survey/ =home
    
    path('',views.animals,name='animals'),
    path('detail/<int:id>/',views.detail,name='detail'),
    path('edit/<int:id>/',views.edit,name='edit'),
    path('create/',views.create,name='create'),
    path('delete/<int:id>/',views.delete,name='delete')
   
    
]

crud_django/base/urls.py
from django.urls import path , include
from . import views 
from django.contrib.auth.views import LogoutView
app_name='application'
urlpatterns = [
    #ex : /survey/ =home
    
    path('',views.TaskList.as_view(),name='taskList'),
    path('task/<int:pk>/',views.TaskDetail.as_view(),name='detail'),
    path('task/create/',views.TaskCreate.as_view(),name='create'),
    path('task/update/<int:pk>/',views.TaskUpdate.as_view(),name="update"),
    path('task/history/',views.TaskHistory.as_view(),name='history'),
    path('task/delete/<int:pk>/',views.TaskDelete.as_view(),name="delete"),
    path('task/login/',views.TaskLogin.as_view(),name='login'),
    path('task/logout/',LogoutView.as_view(next_page='application:login'),name='logout'),
    path('task/register/',views.TaskRegister.as_view(),name='register'),
    
    
   
    
]

crud_django/crud_django/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('animals/',include('animals.urls')),
    path('base/',include('base.urls'))
]

crud_django/animals/models.py
from django.db import models

# Create your models here.

class Animals(models.Model):
    
    name=models.CharField(max_length=200,blank=False,null=False)
    species=models.CharField(max_length=200,blank=False,null=False)
    color=models.CharField(max_length=200,blank=False,null=False)
    extintion_warming=models.BooleanField()
    def __str__(self) :
        return self.name
   

crud_django/base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model):
    #combination of null and black means is optional to fill and is possible to save as ""in the data base
    user= models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    title= models.CharField(max_length=200)
    description=models.TextField(max_length=300,null=True,blank=True)
    complete= models.BooleanField(default=False)
    created=models.DateField(auto_now_add=True)
    def __str__(self):
        return self.title
    class Meta:
        #need to study this comand
        ordering=['complete']
         

crud_django/animals/forms.py
from dataclasses import fields
from django.forms import ModelForm
from .models import Animals
class AnimalForm(ModelForm):
    class Meta():
        model= Animals
        fields='__all__'

crud_django/animals/views.py
#imports
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Animals
from .forms import AnimalForm
#views
def animals(request):
    animals=Animals.objects.all()
    return render(request,'animals/home.html',{'animals':animals})
    
def detail(request,id):
    detail=get_object_or_404(Animals,id=id)
    return render(request,'animals/detail.html',{'detail':detail})

def edit(request,id):
    
    animal=get_object_or_404(Animals,id=id)
    if request.method=='POST':


        animal_form=AnimalForm(request.POST,instance=animal)
        if animal_form.is_valid(): 
            animal_form.save()
            return redirect('aplication:animals')
    else:
        animal_form=AnimalForm()
        return render(request,'animals/edit.html',{'animal_form':animal_form})

def create(request):
    if request.method == 'POST':
        animal_form= AnimalForm(request.POST)
        if animal_form.is_valid():
            animal_form.save()
            return redirect('aplication:animals')
    else:
        animal_form=AnimalForm()
    return render(request,'animals/create.html',{'animal_form':animal_form})
def delete(request,id):
    animal=get_object_or_404(Animals,id=id)
    if animal:
        animal.delete()
        return redirect('aplication:animals')
def home(request):
    pass

crud_django/base/views.py
from multiprocessing import context
from turtle import title
from urllib import response
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Task
from django.shortcuts import render, redirect 
from django.views.generic.edit import CreateView, UpdateView, DeleteView,FormView
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.db.models import Q
# Create your views here.

 
class TaskList(LoginRequiredMixin,ListView):
    '''Show home page'''
    model=Task
    #to change the default variable 
    context_object_name= 'tasks'
    def get_queryset(self):
        '''show value by input, or give all items with complete false and correspond to user '''
        search_input=self.request.GET.get('search_area')
        if search_input:

            objects=Task.objects.filter(complete=False,user=self.request.user,title__icontains=search_input)
            return objects
        else:
            objects=Task.objects.filter(complete=False,user=self.request.user)
            return objects
    

    
class TaskHistory(LoginRequiredMixin,ListView):
    model=Task
    context_object_name= 'history'
    template_name='base/history.html'
    def get_queryset(self):
        '''this function show all items which have been completed'''
        search_input=self.request.GET.get('search_area')
        if search_input:

            objects=Task.objects.filter(complete=False,user=self.request.user,title__icontains=search_input)
            return objects
        else:
            objects=Task.objects.filter(complete=False,user=self.request.user)
            return objects
        
    
class TaskDetail(LoginRequiredMixin,DetailView):
    model= Task
    context_object_name='task'
    #to modify default template name
    template_name='base/task.html'
class TaskCreate(LoginRequiredMixin,CreateView):
    model=Task
    fields=['title','description',]
    success_url= reverse_lazy('application:taskList')    
    template_name='base/create.html'
    def form_valid(self,form):
        form.instance.user=self.request.user
        #TaskCreate the same as the name class
        return super(TaskCreate,self).form_valid(form)
class TaskUpdate(LoginRequiredMixin,UpdateView):
    model=Task
    fields=['title','description','complete']
    template_name='base/task_update.html'
    success_url= reverse_lazy('application:taskList')  
class TaskDelete(LoginRequiredMixin,DeleteView):
    model=Task    
    template_name='base/task_delete.html'
    success_url= reverse_lazy('application:history')  

class TaskLogin(LoginView):
    '''Create a new user'''
    template_name: str='base/login.html'
    fields='__all__'
    redirect_authenticated_user: bool=True
    def get_success_url(self) -> str:

        return reverse_lazy('application:taskList')
class TaskRegister(FormView):
    '''create a new user'''
    template_name: str="base/register.html" 
    form_class=UserCreationForm 
    redirect_authenticated_user=True
    success_url= reverse_lazy('application:taskList')
    def form_valid(self,form):
        '''valid the informacion and save it'''
        user=form.save()
        if user is not None:
            login(self.request,user)

        return super(TaskRegister,self).form_valid(form) 
    def get(self,*args, **kwargs):
        '''if the user is already log in go to tasklist, another hand go to TaskRegister page'''
        if self.request.user.is_authenticated:
            return redirect('application:taskList')
        return super(TaskRegister,self).get(*args, **kwargs)


# def handler404(request,*args,**argv):
#     response=render_to_response('404.html',{},context_instance=RequestContext(request))
#     response.status_code=404
#     return response

# def handler500(request,*args,**argv):
#     response=render_to_response('500.html',{},context_instance=RequestContext(request))
#     response.status_code = 500
#     return response

crud_django/animals/templates/animals/create.html
<form method="POST">
    {% csrf_token %}
    {{animal_form.as_p}}
    <button type='submit'>Create</button>
</form>

crud_django/animals/templates/animals/detail.html
<div class='container'>

<p>{{detail.name}}</p>
<p>{{detail.species}}</p>
<p>{{detail.color}}</p>
<p>{{detail.extintion_warming}}</p>

</div>

crud_django/animals/templates/animals/edit.html
<form method="POST">
    {% csrf_token %}
    {{animal_form.as_p}}
    <button type='submit'>Guardar</button>
</form>

crud_django/animals/templates/animals/home.html
{% load static %}
<link rel="stylesheet" href="{% static '../../static/bootstrap.min.css' %}">

{% if animals %}
<div class='container'>
<a href="{% url 'aplication:create' %}" class ='btn btn-outline-dark mt-5'>Crear Nuevo</a>
<table class="table table-bodered table-info mt-5 text-center">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Name</th>
        <th scope="col">color</th>
        <th scope="col">extincion status</th>
      </tr>
    </thead>
    <tbody>
        {% for  animal in animals%}
      <tr>
        <th>{{animal.id}}</th>
        <td>{{animal.name}}</td>
        <td>{{animal.color}}</td>
        <td>{{animal.species}}</td>         
        <td>{{animal.extintion_warming}}</td>
        <td>
            <a href="{% url 'aplication:detail' animal.id %}" class="btn btn-danger m1-1">Ver mas</a>
            <a href="{% url 'aplication:edit' animal.id %}" class="btn btn-succes m1-1">Editar</a>
            <a href="{% url 'aplication:delete' animal.id %}" class="btn btn-primary m1-1">Eliminar</a>

        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>  
        
           
            
            
            
        
    
{% else %}
    <p>No data avalilable</p>

{% endif %}

crud_django/base/templates/base/create.html
<h1>Task Form:{{object}}</h1>
<a href="{%url 'application:taskList'%}">Go back</a>
<form method="POST" action="">{% csrf_token %}
        {{form.as_p}}
<input type="submit" value="submit">

</form>

crud_django/base/templates/base/history.html
<h1>History</h1>
{% comment %} maybe when you use only the name of the path without application: only works on older version of django {% endcomment %}
<a href="{%url 'application:taskList'%}">Go back </a>
{% if history %}
<form accion="{% url 'application:taskList' %}" method='get'>
    <input type="text" name='search_area'placeholder='Search...'>
    
</form>
<table>
    <tr>
        <th>Task</th>
        <th>Date</th>
    </tr>
    {% for task in history %}
    <tr>
        <td>{{task.title}}</td>
        <td>{{task.created}}</td>
        <td><a href="{%url 'application:delete' task.id %}">Delete</a></td>
        <td><a href="{%url 'application:detail' task.id %}">Detail</a></td>
    </tr>
    
        
    {% endfor %}
</table>
{% else %}
<h3>No haven't had completed tasks yet</h3>
{% endif %}

crud_django/base/templates/base/login.html
<h1>Login</h1>

<form method="post">{% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Login">
</form>

<p>Don't have an account yet?</p> <a href="{%url "application:register"%}">Register</a>

crud_django/base/templates/base/task.html
<a href="{%url 'application:taskList'%}">Go back </a>
<h1>Detail</h1>
<p>task=  {{task}}</p>
<p>desciption</p>
{% if task.description %}
<p>{{task.description}}</p>
{% else %}
<p>No description</p>
{% endif %}

<p>Status= {{task.complete}}</p>

crud_django/base/templates/base/task_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
    
</form>
<a href="{%url 'application:taskList'%}">Go back </a>

crud_django/base/templates/base/task_list.html
{%if request.user.is_authenticated %}
<p>{{request.user}}</p>
<a href="{%url 'application:logout'%}">Log out</a>
{% else %}
<a href="{% url 'application:login' %}">Login</a>
{% endif %}

<hr>

<a href="{% url 'application:taskList' %}"><h1>My to do list</h1></a>

{% comment %} maybe when you use only the name of the path without application: only works on older version of django {% endcomment %}


<a href="{% url 'application:create' %}">Add task</a>
<a href="{%url 'application:history'%}">History</a>
{% if tasks %}
<form accion="{% url 'application:taskList' %}" method='get'>
    <input type="text" name='search_area'placeholder='Search...'>
    
</form>
<table>
    <tr>
        <th>Task</th>
    </tr>
    {% for task in tasks %}
    <tr>
        <td>{{task.title}}</td>
        <td><a href="{%url 'application:detail' task.id%}">Detail</a></td>
        <td><a href="{%url 'application:update' task.id %}">Update</a></td>
    </tr>        
    {% endfor %}
</table>
{% else %}
<h3>No items in list yet</h3>
<a href="{% url 'application:taskList' %}">Home</a>
{% endif %}

crud_django/base/templates/base/task_update.html
<h1>Update</h1>

<a href="{%url 'application:taskList'%}">Go back </a>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>